"""Followup RFE: readable section name

Will only be displayed in admin pages, not exposed to the general public.
Fixes #8 (github)

Revision ID: 72b9fee362f8
Revises: ba0bbd1660c5
Create Date: 2017-05-12 17:40:44.822833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b9fee362f8'
down_revision = 'ba0bbd1660c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode_section', sa.Column('readable_name', sa.Unicode(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode_section', 'readable_name')
    # ### end Alembic commands ###
